"use client";

import { useState } from "react";
import Link from "next/link";
import type { Route } from "next";
import { Badge, Button, Panel } from "../../../../components/ui";

export default function WorkforceSchedulingPage() {
  const [schedules] = useState([
    {
      id: "sch-1",
      name: "Q3 Plant Alpha Production Schedule",
      department: "Warehouse & Manufacturing",
      period: "Sep 01 - Sep 30, 2026",
      targetHC: 120,
      scheduledHC: 120,
      coverage: "100%",
      understaffedHours: 0,
      autoGenerated: true,
      status: "PUBLISHED"
    },
    {
      id: "sch-2",
      name: "Nashik Cold Storage Distribution Roster",
      department: "Logistics",
      period: "Sep 01 - Sep 15, 2026",
      targetHC: 40,
      scheduledHC: 38,
      coverage: "95%",
      understaffedHours: 8,
      autoGenerated: true,
      status: "PUBLISHED"
    }
  ]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <div className="flex items-center gap-2">
            <Link href={"/attendance/command-center" as Route} className="text-sm font-medium text-slate-500 hover:text-slate-800">
              ← Attendance Center
            </Link>
          </div>
          <h1 className="text-2xl font-bold text-slate-900 mt-1">⚡ Workforce Scheduling & Skill Coverage Engine</h1>
          <p className="text-sm text-slate-600">
            Auto-generate balanced shift rosters matching production demand, skill certifications, leave availability, and fatigue limits.
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="primary">⚡ Run Auto-Scheduler</Button>
        </div>
      </div>

      {/* Schedules Table */}
      <Panel className="space-y-4">
        <h2 className="text-lg font-bold text-slate-900">Active Schedules & Coverage Plans ({schedules.length})</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-slate-600">
            <thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-500 font-semibold">
              <tr>
                <th className="py-3 px-4">Schedule Title</th>
                <th className="py-3 px-4">Department</th>
                <th className="py-3 px-4">Schedule Horizon</th>
                <th className="py-3 px-4">Target / Scheduled HC</th>
                <th className="py-3 px-4">Skill Coverage</th>
                <th className="py-3 px-4">Engine Mode</th>
                <th className="py-3 px-4">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {schedules.map((s) => (
                <tr key={s.id} className="hover:bg-slate-50/50">
                  <td className="py-3.5 px-4 font-semibold text-slate-900">{s.name}</td>
                  <td className="py-3.5 px-4 text-xs text-slate-600">{s.department}</td>
                  <td className="py-3.5 px-4 font-mono text-xs">{s.period}</td>
                  <td className="py-3.5 px-4 font-mono font-bold text-slate-900">{s.scheduledHC} / {s.targetHC}</td>
                  <td className="py-3.5 px-4">
                    <Badge tone={s.coverage === "100%" ? "success" : "warning"}>{s.coverage} Coverage</Badge>
                  </td>
                  <td className="py-3.5 px-4">
                    <Badge tone="neutral">AUTO-OPTIMIZED</Badge>
                  </td>
                  <td className="py-3.5 px-4">
                    <Badge tone="success">{s.status}</Badge>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>
    </div>
  );
}
